## Checking Clocksync Setting
---
- hosts: all

  become: yes

  tasks:
  - name: Check closksync
    shell: ntpstat
    register: output
    failed_when: "output.rc != 0"
  - debug:
       msg: "ERROR System clock is currently not synchronised"
