## Checking Docker folder size
---
- hosts: all

  become: yes

  vars_files:
   - ../../vars/globals.yml

  vars:
    dickersize: "{{ docker_storage_size }}"

  tasks:
  - name: Check directory exists
    stat:
       path: "{{ docker_storage }}"
    register: docker_dir

  - name: Populate Variable via Shell Command
    shell: df -h $(df -P /var/lib/docker | tail -1 | cut -d' ' -f 1) --output=avail | tail -1 | sed 's/G//g'
    register: dockersize
    ignore_errors: True
    
  - name: Validate docker directory size
    shell: echo "ERROR Current {{ docker_storage }} size is {{ dockersize.stdout }}. The minimum recommended is 200GB"
    register: output
    failed_when: (dockersize.stdout|int) < (dickersize|int)
