## Checking Hostname in lowercase characters
---
- hosts: all
  gather_facts: yes

  tasks:
  - name: Populate Variable via Shell Command
    shell: hostname | grep [A-Z] | wc -l
    register: host
    ignore_errors: True
  #- debug:
       #msg: "Current host settings is {{host.stdout}}"

  - name: Hostname Check
    shell: echo "ERROR Only lowercase characters are supported in the hostname"
    register: output
    failed_when: host.stdout != "0"
