## Checking kernel OS patch
---
- hosts: all
  gather_facts: yes

  vars_files:
   - ../../vars/globals.yml

  vars:
    kernelpatchlevel: "{{ kernel_patch_level }}"

  tasks:
  - name: Populate Variable via Shell Command Patch
    #shell: uname -r
    shell: p1=`uname -r | awk -F"-" '{print $1}'`; p2=`uname -r | awk -F"-" '{print $2}'|awk -F"." '{print $1}'`;echo "$p1-$p2"
    register: patchversion
    ignore_errors: True

  - debug:
       msg: "Current OS patch level is {{ patchversion.stdout }}"

  - name: OS Patch Version Check
    shell: echo "ERROR The OS patch version must be {{ kernelpatchlevel }}"
    register: output
    failed_when: (patchversion.stdout not in kernelpatchlevel)
