## Checking OS Version
---
- hosts: all
  gather_facts: yes

  vars_files:
   - ../../vars/globals.yml

  tasks:
  - name: OS Distribution
    debug:
      msg: "Current OS version: {{ ansible_distribution_version }}"

  - name: OS Distribution Check
    shell: echo "ERROR The OS version must be RedHat 7.6 or 7.7"
    register: output
    failed_when: (ansible_distribution_version not in suported_os_version)
